    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aakrutinirmal
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userprocesscontainer;
private Enterprise enterprise;
private UserAccount account;
private Organization organization;
private EcoSystem ecoSystem;
    /**
     * Creates new form PatientRoleJPanel
     */
    public PatientWorkAreaJPanel(JPanel userprocesscontainer,UserAccount account,Organization organization, Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.ecoSystem=ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vitalSignsjButton = new javax.swing.JButton();
        inboxjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patient Work Area");

        vitalSignsjButton.setText("Patient Details");
        vitalSignsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalSignsjButtonActionPerformed(evt);
            }
        });

        inboxjButton.setText("Inbox");
        inboxjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxjButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/493316570.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(vitalSignsjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(inboxjButton)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(vitalSignsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inboxjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vitalSignsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalSignsjButtonActionPerformed
        // TODO add your handling code here:
        ManageVitalSignsJPanel manageVitalSignsJPanel = new ManageVitalSignsJPanel(userprocesscontainer,account,organization,enterprise, ecoSystem);
        userprocesscontainer.add("ManageVitalSignsJPanel", manageVitalSignsJPanel);
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_vitalSignsjButtonActionPerformed

    private void inboxjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxjButtonActionPerformed
        // TODO add your handling code here:
      CheckInboxJPanel checkInboxJPanel = new CheckInboxJPanel(userprocesscontainer,account,organization,enterprise, ecoSystem);
        userprocesscontainer.add("CheckInboxJPanel", checkInboxJPanel);
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);  
    }//GEN-LAST:event_inboxjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inboxjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton vitalSignsjButton;
    // End of variables declaration//GEN-END:variables
}
